<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Progression\**" />
    <EmbeddedResource Remove="Progression\**" />
    <None Remove="Progression\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Open.Threading.Dataflow" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Solve.Experiment\Solve.Experiment.csproj" />
    <ProjectReference Include="..\..\..\Solve\Solve.csproj" />
    <ProjectReference Include="..\Core\Eater.Core.csproj">
      <TreatAsUsed>true</TreatAsUsed>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <None Update="Seeds.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>